# @package _global_
trainer:
  profiler:
    _target_: pytorch_lightning.profiler.PyTorchProfiler
    filename: profile
    dirpath: ???
    schedule:
      _target_: torch.profiler.schedule
      skip_first: 2
      wait: 0
      warmup: 2
      active: 5
  max_epochs: 1
  limit_train_batches: 10
  limit_val_batches: 1
