# @package _global_
trainer:
  callbacks:
    - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      refresh_rate: 1
    - _target_: mammography.src.train.SubmissionWriter
      write_interval: epoch
      output_filepath: submission.csv
  logger:
    job_type: submission
ckpt_path: ???
