tif_dir: /kaggle/input/mayo-clinic-strip-ai/train/
metadata_path: /kaggle/input/mayo-clinic-strip-ai/train.csv
roi_path: /kaggle/input/mayo-rois/train/ROIs.csv
hyperparameters:
  data:
    batch_size: 16
    crop_size: 512
    epochs: 10
  model:
    backbone_fn: densenet161
    weights: DenseNet161_Weights.DEFAULT
    max_grad_norm: 1.0
  optimizer:
    cls: AdamW
    lr: 0.002
    weight_decay: 0.001
