tif_dir: /kaggle/input/mayo-clinic-strip-ai/train/
metadata_path: /kaggle/input/mayo-clinic-strip-ai/train.csv
roi_path: /kaggle/input/mayo-rois/train/ROIs.csv
prefetch_batches: 8
hyperparameters:
  data:
    batch_size: 16
    crop_size: 2048
    final_size: 256
    epochs: 10
    stratification_levels:
      - label
      - center_id
      - patient_id
  model:
    backbone_fn: densenet161
    weights: DenseNet161_Weights.DEFAULT
    max_grad_norm: 1.0
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.002
    weight_decay: 0.001
