trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: ???
  benchmark: true
  precision: 16
  callbacks:
    - _target_: mammography.src.submit.SubmissionWriter
      write_interval: epoch
      output_filepath: submission.csv
    # - _target_: mammography.src.train.BatchSizeFinder
    #   inference:
    #     mode: binsearch
    #     batch_arg_name: inference_batch_size
    #     init_val: 20
datamodule:
  _target_: mammography.src.data.datamodule.DataModule.load_from_checkpoint
  checkpoint_path: ${ckpt_path}
  image_dir: ???
  metadata_paths:
    predict: ???
  prefetch_factor: 4
model:
  _target_: mammography.src.model.lightning_module.Model.load_from_checkpoint
  checkpoint_path: ${ckpt_path}
seed_fn:
  _target_: pytorch_lightning.utilities.seed.seed_everything
  seed: 42
  workers: true
ckpt_path: ???
