trainer:
  _target_: pytorch_lightning.Trainer
  callbacks:
    - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      refresh_rate: 1
    - _target_: mammography.src.submit.SubmissionWriter
      write_interval: epoch
      output_filepath: submission.csv
datamodule:
  _target_: mammography.src.data.DataModule.load_from_checkpoint
  checkpoint_path: ???
  image_dir: ???
  prefetch_factor: 4
model:
  _target_: mammography.src.model.Model.load_from_checkpoint
  checkpoint_path: ???
seed_fn:
  _target_: pytorch_lightning.utilities.seed.seed_everything
  seed: 42
  workers: true
