trainer:
  _target_: pytorch_lightning.Trainer
  # auto_scale_batch_size: binsearch
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      mode: &mode max
      every_n_epochs: 1
      save_top_k: 1
      verbose: true
      monitor: &monitor metrics/pf1/val
    - _target_: pytorch_lightning.callbacks.TQDMProgressBar
    - _target_: pytorch_lightning.callbacks.EarlyStopping
      monitor: *monitor
      verbose: true
      mode: *mode
      divergence_threshold: 0.1
      patience: 5
  gradient_clip_val: 1.0
  gradient_clip_algorithm: value
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  benchmark: true
  max_epochs: 10
  precision: 16
  default_root_dir: ???
  accumulate_grad_batches: 1
  logger:
    - _target_: pytorch_lightning.loggers.WandbLogger
      project: rsna-breast-cancer-detection
datamodule:
  _target_: mammography.src.train.DataModule
  metadata_filepath: ???
  image_dir: ???
  batch_size: 23
  prefetch_batches: 1
  augmentation:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torchvision.transforms.RandomCrop
        size: 512
        pad_if_needed: true
model:
  _target_: mammography.src.train.Model
  optimizer_config:
    _target_: torch.optim.AdamW
    lr: 1e-3
    weight_decay: 0.2
    _partial_: true
  feature_extractor:
    _target_: mammography.src.train.FeatureExtractor
    backbone:
      _target_: torchvision.models.densenet161
      memory_efficient: false
      pretrained: false
    layer_name: flatten
  classifier:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.Linear
        in_features: 2208
        out_features: 1
      # - _target_: torch.nn.Sigmoid
