trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: ???
  plugins:
    _target_: pytorch_lightning.plugins.io.AsyncCheckpointIO
    checkpoint_io:
      _target_: pytorch_lightning.plugins.io.TorchCheckpointIO
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      mode: &mode max
      every_n_epochs: 1
      save_last: false
      save_top_k: 1
      verbose: true
      monitor: &monitor cancer/pf1/val
    - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      refresh_rate: 1
    - _target_: pytorch_lightning.callbacks.EarlyStopping
      monitor: *monitor
      verbose: true
      mode: *mode
      patience: 10
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
      log_momentum: true
    - _target_: pytorch_lightning.callbacks.ModelSummary
      max_depth: 3
    # - _target_: mammography.src.train.BatchSizeFinder
    #   training:
    #     mode: binsearch
    #     batch_arg_name: train_batch_size
    #     init_val: ${datamodule.train_batch_size}
    #     steps_per_trial: 10
    #   inference:
    #     mode: binsearch
    #     batch_arg_name: inference_batch_size
    #     init_val: ${datamodule.inference_batch_size}
    #     steps_per_trial: 10
  gradient_clip_val: 1e1
  gradient_clip_algorithm: value
  log_every_n_steps: 20
  num_sanity_val_steps: 0
  benchmark: true
  max_epochs: 50
  precision: 16
  # accumulate_grad_batches: 1
  logger:
    _target_: mammography.src.ptl_patches.WandbLogger
    project: rsna-breast-cancer-detection
    job_type: training
    log_model: true
    save_dir: ???
    settings:
      _target_: wandb.Settings
      code_dir: /mammography/mammography
datamodule:
  _target_: mammography.src.data.datamodule.DataModule
  image_dir: ???
  metadata_paths:
    train: ${datamodule.image_dir}/train.json
    val: ${datamodule.image_dir}/val.json
  train_batch_size: 11
  inference_batch_size: 22
  prefetch_factor: 55
  augmentation:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: mammography.src.data.transforms.ToTensor
      # - _target_: mammography.src.data.transforms.CropCenterRight
      #   height: 3000
      #   width: 2000
      # - _target_: torchvision.transforms.Resize
      #   size: 511
      #   max_size: 512
      # - _target_: mammography.src.data.CLAHE
      #   clipLimit: 2.0
      #   tileGridSize: [32, 32]
      # - _target_: torchvision.transforms.RandomHorizontalFlip
      # - _target_: torchvision.transforms.RandomAffine
      #   degrees: 40.0
      #   translate:
      #     - 0.2
      #     - 0.2
      #   scale:
      #     - 0.8
      #     - 1.2
      #   shear:
      #     - 0.2
      #     - 0.2
      # - _target_: torchvision.transforms.CenterCrop
      #   size: 512
  resizer:
    _target_: mammography.src.data.transforms.ResizeLookup
    lookup_table:
      21: 0.47919092100021615
      29: 0.26131120123586693
      48: 0.31130864310021933
      49: 0.33649462625088383
      93: 0.4776470506067665
      170: 0.35170585038041563
      190: 0.5138467491903878
      197: 0.5735921797664861
      210: 0.26051742179411685
      216: 0.5442852854636264
    default: 0.4109899928788986
  cropper:
    _target_: mammography.src.data.transforms.CropCenterRight
    height: 512
    width: 300
model:
  _target_: mammography.src.model.lightning_module.Model
  optimizer_config:
    _convert_: all
    optimizer:
      _target_: torch.optim.AdamW
      lr: 2e-5
      weight_decay: 1e-2
      _partial_: true
    lr_scheduler:
      scheduler:
        _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
        _partial_: true
        mode: *mode
        factor: 0.5
        patience: 5
        cooldown: 3
        verbose: true
      interval: epoch
      monitor: *monitor
  loss:
    _target_: mammography.src.loss.MultiLoss
    cancer:
      _target_: torch.nn.BCEWithLogitsLoss
    # density:
    #   _target_: torch.nn.BCEWithLogitsLoss
  net:
    _target_: mammography.src.model.modules.Network
    image_fuser:
      _target_: mammography.src.model.modules.ImageFuser
      feature_extractor:
        _target_: builtins.getattr
        _args_:
          - _target_: torchvision.models.efficientnet_b6
            weights: IMAGENET1K_V1
          - features
      pool:
        _target_: torch.nn.AdaptiveMaxPool2d
        output_size: 1
      neck:
        _target_: torch.nn.Sequential
        _args_:
          # - _target_: torch.nn.LazyConv2d
          #   out_channels: 96
          #   kernel_size: 3
          # - _target_: torch.nn.LazyBatchNorm2d
          # - _target_: torch.nn.ReLU
          #   inplace: true
          - _target_: torch.nn.AdaptiveMaxPool2d
            output_size: 1
          - _target_: torch.nn.Flatten
    neck:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: torch.nn.LazyLinear
          out_features: 1
    # _target_: mammography.src.model.replace_submodules
    # _convert_: all
    # module:
    #   _target_: torchvision.models.efficientnet_b6
    #   drop_rate: 0.0
    #   weights: IMAGENET1K_V1
    # # features.0.0:
    # #   in_channels: 1
    # classifier.1:
    #   out_features: 1
seed_fn:
  _target_: pytorch_lightning.utilities.seed.seed_everything
  seed: 42
  workers: true
