trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: ???
  # auto_scale_batch_size: binsearch
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      mode: &mode max
      every_n_epochs: 1
      save_last: true
      save_top_k: 1
      verbose: true
      monitor: &monitor metrics/pf1/val
      dirpath: ${trainer.default_root_dir}/checkpoints
    - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      refresh_rate: 1
    - _target_: pytorch_lightning.callbacks.EarlyStopping
      monitor: *monitor
      verbose: true
      mode: *mode
      patience: 5
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
      log_momentum: true
  # gradient_clip_val: 1.0
  # gradient_clip_algorithm: value
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  benchmark: true
  max_epochs: 10
  precision: 16
  default_root_dir: ???
  # accumulate_grad_batches: 1
  logger:
    _target_: mammography.src.ptl_patches.WandbLogger
    project: rsna-breast-cancer-detection
    job_type: training
    log_model: all
    save_dir: ${trainer.default_root_dir}
    settings:
      _target_: wandb.Settings
      code_dir: /kaggle/working/kaggle
datamodule:
  _target_: mammography.src.data.DataModule
  metadata_filepath: ???
  image_dir: ???
  batch_size: 8
  prefetch_factor: 3
  augmentation:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: mammography.src.data.CropCenterRight
        size: 2048
      - _target_: torchvision.transforms.Resize
        _convert_: object
        size: 512
      - _target_: mammography.src.data.MinMaxScale
      # - _target_: torchvision.transforms.RandomHorizontalFlip
      # - _target_: torchvision.transforms.RandomAffine
      #   _convert_: object
      #   degrees: 40.0
      #   translate:
      #     - 0.2
      #     - 0.2
      #   scale:
      #     - 0.8
      #     - 1.2
      #   shear:
      #     - 0.2
      #     - 0.2
      # - _target_: torchvision.transforms.CenterCrop
      #   size: 512
model:
  _target_: mammography.src.model.Model
  optimizer_config:
    _convert_: all
    optimizer:
      _target_: torch.optim.Adam
      lr: 1e-3
      # momentum: 0.9
      weight_decay: 0.0
      _partial_: true
    lr_scheduler:
      scheduler:
        _target_: torch.optim.lr_scheduler.ConstantLR
        _partial_: true
        factor: 1.0
      interval: step
  feature_extractor:
    _target_: mammography.src.model.replace_submodules
    _convert_: all
    module:
      _target_: torchvision.models.efficientnet_b4
      drop_rate: 0.0
      num_classes: 1
    features.0.0:
      in_channels: 1
seed_fn:
  _target_: lightning_lite.utilities.seed.seed_everything
  seed: 42
  workers: true
